# Используем более легкий базовый образ
FROM python:3.13-slim

# Установка системных зависимостей одним слоем
RUN apt-get update && apt-get install -y \
    curl wget unzip git \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# Копируем и устанавливаем Python зависимости
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# Устанавливаем браузеры для Playwright
RUN python -m playwright install --with-deps chromium

# Создаем рабочую директорию
WORKDIR /tests

# Копируем тесты
COPY tests/ ./tests/
COPY run_tests_ci.sh ./
RUN chmod +x run_tests_ci.sh

CMD ["./run_tests_ci.sh"]