name: Run Tests & Publish Allure Report

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Клонирование репозитория
      uses: actions/checkout@v3

    - name: 🐍 Установка Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: 📦 Установка зависимостей
      run: |
        pip install allure-pytest pytest-playwright
        playwright install --with-deps

    - name: ⚙️ Установка Allure CLI
      run: |
        sudo npm install -g allure-commandline --save-dev

    - name: 🚀 Запуск тестов с Allure
      run: |
        chmod +x ./run_tests_ci.sh
        ./run_tests_ci.sh

    - name: 🌐 Публикация Allure отчёта на GitHub Pages
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./allure-report